{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "clamav.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "clamav.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end -}}